version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: final-project
    container_name: flask-finalproject
    ports:
      - "5007:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
